version: "2"
services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.app
      args:
        ruby_version: 2.4.0
    ports:
      - "3000:3000"
    command: bash -i -c './bin/rails s -b 0.0.0.0 -p 3000'
    volumes:
      - .:/mobishelf
      - gem-data:/root/.rbenv/versions/2.4.0/lib/ruby/gems
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  gem-data:
    driver: local
  mysql-data:
    driver: local
