default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: db

development:
  <<: *default
  database: fumifumi_development

test:
  <<: *default
  database: fumifumi_test

production:
  <<: *default
  database: fumifumi_production
  username: fumifumi
  password: <%= ENV['FUMIFUMI_DATABASE_PASSWORD'] %>
